# Generated by Django 5.2.8 on 2025-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
